id: f6ec2f8e613d4909bbb56f9feb251d69
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_182-The_Perfection_of_Generosity-v2
  language: bo
  author: ''
  volume: {}
